config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'homes#top'
  get 'homes/about' => 'homes#about'
 
  resources :posts, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index, :destroy] do
     member do
      put "/users/:id/hide" => "users#hide", as: 'users_hide'
    end
  resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  private
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user 
  belongs_to :post 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
  
  validates :title, presence: true
  validates :image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  attachment :profile_image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
   # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @post = Post.find(params[:post_id])
    favorite = @post.favorites.new(user_id: current_user.id)
    favorite.save
    
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    favorite = @post.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.post_id = @post.id
    @post_comment.user_id = current_user.id
    @post_comment.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    post_comment = @post.post_comments.find(params[:id])
    post_comment.destroy
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
     redirect_to post_path(@post)
    else
     render :new
    end
  end

  def index
    @posts = Post.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.user_id = current_user.id
    @post.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :remark, :image)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
	def create
	 current_user.follow(params[:user_id])
	 redirect_to request.referer
	end

	def destroy
	 current_user.unfollow(params[:user_id])
	 redirect_to request.referer
	end
  def followings
	 user = User.find(params[:user_id])
	 @users = user.followings
  end

  def followers
	 user = User.find(params[:user_id])
	 @users = user.followers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
    @post = Post.new
  end
  
  def hide
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会しました。またのご利用をお待ちしております。"
    redirect_to root_path
  end
  
  def index
    @users = User.all
    @posts = Post.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if post.favorited_by?(current_user) %>
  <%= link_to post.favorites.count, post_favorites_path(post), method: :delete, remote: true,  class: "glyphicon glyphicon-heart" %>
<% else %>
  <%= link_to post.favorites.count, post_favorites_path(post), method: :post, remote: true, class: "glyphicon glyphicon-heart-empty" %>
<% end %>

app/views/favorites/create.js.erb
$("#post_<%= @post.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', post: @post) %>");

app/views/favorites/destroy.js.erb
$("#post_<%= @post.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', post: @post) %>");

app/views/homes/about.html.erb
<div class="row_about">
    <div class="col-xs-12">
    <h1 class="about-title">Share-Thinkとは？</h1>
      <h3 class="text-center">
        あなたが考えてるいること、悩んでいることを</br>
        自由に投稿できるサイトです。</br>
        あなたの悩みや考えを風景、写真とともに言語化し、</br>
        考えをまとめたり、備忘録としてご利用ください。</br>
        あなたの投稿が他のユーザーに気づきを与えたり、</br>
        あなただけの名言が生まれるかもしれません。</br>
      </h3>
      <div class="text-center"><%= image_tag "about.jpg", size:"500x400" %></div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="row">
  <h2 class="top-welcome">ようこそShare-Thinkへ</h2>
  <div class="text-center"><%= image_tag "shop.jpg", size:"500x400" %></div>
  <div class="top_block">
  <p><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up btn' %></p>
  <p><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in btn'%></p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p class="footer-text">CopyRight RyuseiIshida.inc</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
   <div class="nav nav-pills navbar-left">
    <%= link_to image_tag('logo.jpg', class:'image_logo'), '/' %>
   </div>
    <nav>
      <ul class="nav nav-pills pull-right">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li class="nav-item"><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li class="nav-item"><%= link_to ' Think', posts_path, class: 'glyphicon glyphicon-book books'%></li>
          <li class="nav-iteme"><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About', homes_about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share-Think</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class='body'>
      <div class='container'>
        <p id="notice"><%= notice %></p>

        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/post_comments/_index.html.erb
<% post.post_comments.each do |post_comment| %>
  <% post_comment_user = post_comment.user %>
  <tr>
  	<td>
  		<%= link_to user_path(post_comment_user), class: "user_#{post_comment_user.id}" do %>
    		<%= attachment_image_tag post_comment_user, :profile_image, size: "50x50", fallback: "no_image.jpg", size: "50x50" %><br>
    		<%= post_comment_user.name %>
  		<% end %>
  	</td>
  	<td><%= post_comment.comment %></td>
  	<% if current_user == post_comment_user %>
    	<td><%= link_to 'Destroy', post_post_comment_path(post_comment.post_id, post_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
  	<% end %>
  </tr>
<% end %>

app/views/post_comments/create.js.erb
$("#post_<%= @post.id %> .comments-count").html("コメント数: <%= @post.post_comments.count %>");
$(".post_comments").html("<%= j(render 'post_comments/index', post: @post) %>");
$("#post_comment_comment").val("");

app/views/post_comments/destroy.js.erb
$("#post_<%= @post.id %> .comments-count").html("コメント数: <%= @post.post_comments.count %>");
$(".post_comments").html("<%= j(render 'post_comments/index', post: @post) %>");
$("#post_comment_comment").val("");

app/views/posts/_form.html.erb
<%= form_with model:post,local:true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 title' %>
  </div>

  <div class="field row">
    <%= f.label :remark %>
    <%= f.text_area :remark, class: 'col-xs-12 remark'%>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12'%>
  </div>
<% end %>

app/views/posts/_index.html.erb
<div class="row">
  <table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% posts.each do |post| %>
      <tr id="post_<%= post.id %>">
        <td>
          <%= link_to user_path(post.user) do %>
            <%= attachment_image_tag post, :image, size:"80x80", fallback: "no-image-icon.jpg" %>
          <% end %>
        </td>
        <td><%= link_to post.title, post_path(post), class: "post_#{post.id}" %></td>
        <td><%= post.remark %></td>
        <td class="favorite-btn"><%= render "favorites/favorite-btn", post: post %></td>
        <td class="comments-count">コメント数: <%= post.post_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/posts/edit.html.erb
<div class='row'>
	<div class='col-md-6 col-md-offset-3'>
		<h1>Editing Post</h1>
		<%= render 'form', post: @post %>
		<%= link_to 'Show', post_path(@post), class: "post_#{@post.id}" %> |
		<%= link_to 'Back', posts_path, class: "back" %>
    </div>
    <div class='col-md-3'></div>
</div>

app/views/posts/index.html.erb
<div class="row">
   <h2>
      <i class="fa fa-th-list" aria-hidden="true"></i>
        Think
     </h2>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Title</th>
          <th>いいね</th>
          <th></th>
          <th>投稿日</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @posts.each do |post| %>
          <tr id="post_<%= post.id %>">
            <td>
              <%= link_to post_path(post.id) do %>
                <%= attachment_image_tag post, :image, size: '50x50' %>
              <% end %>
            </td>
            <td>
              <%= link_to user_path(post.user) do %>
                <%= post.user.name %>
              <% end %>
            </td>
            <td><%= link_to post.title, post_path(post), class: "post_#{post.id}" %></td>
            <td class="favorite-btn"><%= render "favorites/favorite-btn", post: post %></td>
            <td class="comments-count">コメント数: <%= link_to "#{post.post_comments.count}", post_path(post.id) %></td>
            <td class="created-at"> <%= post.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">


          <div class="col-md-6 col-md-offset-3 post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>New Post</span>
              </h3>
            </div>
            <%= form_with model: @post, local:true do |f| %>
              <% if @post.errors.any? %>
                <div id="error_explanation">
                  <h2><%= @post.errors.count %>件のエラーが発生しました。</h2>
                  <ul>
                  <% @post.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

                <div class="col-sm-12">
                  <%= f.attachment_field :image %>
                </div>

              <br>

                <div class="col-sm-6">
                  <div class="form-group has-icon">

                    <%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
                  </div>
                </div>


                <div class="col-sm-12">
                  <%= f.text_area :remark, class:"form-control", rows:"3", placeholder:"何を考えてる？" %>
                </div>


              <%= f.submit "投稿", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
            <% end %>
　　　　　　</div>

      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<div class="row">
  <div class='col-xs-5'>
    <h2>User info</h2>
    <%= render 'users/info', user: @post.user %>
  </div>


  <div class='col-xs-7'>
		<h2>Post detail</h2>
		<table class='table'>
		  <tr id="post_<%= @post.id %>">
        <td>
          <%= link_to user_path(@post.user_id) do %>
            <%= attachment_image_tag @post, :image, size:"100x100", fallback: "no_image.jpg" %><br>
            <%= @post.user.name %>
          <% end %>
        </td>
        <td><%= link_to @post.title, post_path(@post) %></td>
        <td><%= @post.remark %></td>
        <td class="favorite-btn"><%= render "favorites/favorite-btn", post: @post %></td>
        <td class="comments-count">コメント数: <%= @post.post_comments.count %></td>

        <% if @post.user == current_user %>
          <td><%= link_to 'Edit', edit_post_path(@post), class: "btn-sm btn-success edit_post_#{@post.id}" %></td>
          <td><%= link_to 'Destroy', post_path(@post), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_post_#{@post.id}"%></td>
        <% end %>
      </tr>
    </table>
    <table class="post_comments">
      <%= render 'post_comments/index', post: @post %>
    </table>
    <%= form_with model:[@post,@post_comment],data:{remote:true} do |f| %>
      <%= f.text_area :comment, size:"70x5", placeholder:"あなたの意見は？" %>
      <%= f.submit '送信'%>
    <% end %>
  </div>
</div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_index.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no_image.jpg") %>
        </td>
        <td>
          <%= link_to user_path(user) do %>
          <%= user.name %>
          <% end %>
        </td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary pull-right" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success pull-right" %>
    <% end %>
  <% else %>
    <%= link_to '', edit_user_path(user), class: "col-xs-1 btn btn-default pull-right glyphicon glyphicon-wrench edit_user_#{user.id}" %>
<% end %>
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, fallback: "no_image.jpg", size:"100x100", class:"img-circle") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<!--管理者のみ-->
<% if current_user.admin? %>
    <%= link_to "delete", @user, method: :delete,
                            data: { confirm: "You sure?" }, class: "btn btn-danger" %>
<% end %>



  

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">
          <section class="slice slice-lg sct-color-1">
            <div class="container">
              <div class="row">
                <div class="col-md-4 col-md-offset-4">
                  <div class="form-user style-1 rounded has-shadow-1">
                    <div class="form-header text-center">
                      <h2 class="form-header-title">プロフィール編集</h2>
                    </div>
                    <div class="form-body">

                      <%= form_with model:@user, local:true do |f| %>
                        <div class="form-group has-icon">
                          <label class="control-label sr-only" for="inputEmail">Name</label>
                          <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
                          <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                        </div>
                        <div class="form-group has-icon">
                          <label class="control-label sr-only" for="inputEmail">Introduction</label>
                           <%= f.text_field :introduction, class:"form-control" %>
                        </div>
                        <div class="form-group has-icon">
                          <div class="user-edit-image">
                          <%= attachment_image_tag @user, :profile_image, size: "30x30", class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                          </div>
                          <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
                          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
                        </div>
                        <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                      <% end %>
                      <% if user_signed_in? && @user.id == current_user.id %>
                        <%= link_to "退会", users_hide_user_path(current_user), method: :put, "data-confirm" => "本当に退会しますか？", class: "btn btn-outline-danger" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='row'>
  <h2>
    <i class="fa fa-group" aria-hidden="true"></i>
    Users
  </h2>
    <%= render 'index', users: @users %>
  
</div>

app/views/users/show.html.erb
<div class='row'>

  <div class='col-xs-12'>
    <h2>
    <i class="fa fa-id-card-o" aria-hidden="true"></i>
    User Page
    </h2>
    <%= render 'info', user: @user %>
  </div>




  <div class='col-xs-12'>
    <%= link_to "", "/posts/new", data: {"turbolinks" => false}, class: "pull-right fa fa-plus-circle fa-4x" %>
    <h2>
      <i class="fa fa-pencil" aria-hidden="true"></i>
      Think
    </h2>

    <%= render 'posts/index', posts: @posts %>
  </div>
</div>